# Copyright (c) 2021 Synopsys, Inc. All rights reserved worldwide.
variables:
  ARTIFACTORY_URL: https://artifactory.internal.synopsys.com/artifactory
  ARTIFACTORY_REGISTRY: artifactory.internal.synopsys.com:5002
  ARTIFACTORY_JFROG_URL: $ARTIFACTORY_URL/sigma-local/devops/helpers/jfrog/jfrog.linux_x86_64
